version: '3.5'

services:
    nginx:
        build: ./docker/images/nginx
        ports:
            - "8089:80"
            # - "443:443"
        volumes:
            # - ./docker/hosts:/etc/nginx/conf.d
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./application:/var/www/html
            - ./logs:/var/log/nginx
            - ./letsencrypt:/etc/letsencrypt
            - ./acme-challenge:/var/lib/certbot/.well-known/acme-challenge
        networks:
            - cluster
        links:
            - app
    app:
        build: ./docker/images/php80
        working_dir: /var/www/html
        links:
            - postgresql
            - postgresql_sipout
        external_links:
            - nginx:nginx
        networks:
            - cluster
        volumes:
            - ./application:/var/www/html
    postgresql:
        image: postgres:9.6.21-alpine
        ports:
            - "5431:5432"
        networks:
            - cluster
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: avito
    postgresql_sipout:
        image: postgres:9.6.21-alpine
        ports:
            - "5430:5432"
        networks:
            - cluster
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: sipout
networks:
    cluster:
        name: cluster
        external: true
        driver: bridge

